export const ROUTES = {
    HOME: "/",
    NOT_FOUND: "/notFound",
    ABOUT_US: "/aboutUs",
    CONTACTS: "/contacts",
    FAQ: "/faq",
    PRIVACY_POLICY: "/privacyPolicy",
    MEMBERSHIP: "/membership",
    MASSAGES: "/massages",
    MASSAGE: "/massage/:id",
    FOOT_MASSAGE: "footMassage",
    HAND_MASSAGE: "handMassage",
    HONEY_MASSAGE: "honeyMassage",
    CUPPING_MASSAGE: "cuppingMassage",
    CLASSIC_MASSAGE: "classicBodyMassage",
    FACIAL_MASSAGE: "facialMassage",
    BACK_NACK_MASSAGE: "backNackMassage",
    RELAX_MASSAGE: "relaxMassage",
    NECK_SHOULDER_MASSAGE: "neckShoulderMassage",
    SPORT_MASSAGE: "sportMassage",
}